// Generated by CoffeeScript 1.3.3
(function() {
  var RUN_CONFS, VER, app, config, express, http, manager, mdb, qs, url, util, _ref,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  VER = "ariuspay 0.0.2";

  console.log(("" + VER + " starting at: ") + new Date);

  RUN_CONFS = ["development", "production"];

  util = require('util');

  if (!process.env.NODE_ENV) {
    process.env.NODE_ENV = 'development';
  } else {
    if (_ref = process.env.NODE_ENV, __indexOf.call(RUN_CONFS, _ref) < 0) {
      console.error("NODE_ENV not in " + util.inspect(RUN_CONFS));
      process.exit(1);
    }
  }

  config = require('config');

  express = require('express');

  http = require("http");

  url = require("url");

  qs = require("querystring");

  mdb = require('./mdb');

  app = express.createServer();

  app.configure(function() {
    app.set("views", __dirname + "/views");
    app.set("view engine", 'jade');
    app.set("view options", {
      layout: false,
      pretty: false,
      cache: true
    });
    app.use(express.favicon());
    app.use(express.logger("dev"));
    app.use(express.bodyParser());
    app.use(app.router);
    return app.use('/inc', express["static"](__dirname + "/inc"));
  });

  app.configure("development", function() {
    app.set("view options", {
      layout: false,
      pretty: true,
      cache: false
    });
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure("production", function() {
    return app.use(express.errorHandler());
  });

  manager = require('./manager');

  app.get("/", function(req, res) {
    return res.redirect("/payment/manager/");
  });

  app.get("/payment/manager/", manager.paylist);

  app.get("/payment/manager/newpay", manager.newpay);

  app.post("/payment/manager/newpay", manager.newpay_post);

  app.listen(config.server.port);

}).call(this);
