// Generated by CoffeeScript 1.3.3
(function() {
  var config, du, lib, mdb, util, _x;

  util = require('util');

  du = require('date-utils');

  lib = require('./lib');

  config = require('config');

  mdb = require('./mdb');

  _x = exports || this;

  _x.paylist = function(req, res) {
    return mdb.Orders.find({}).sort('ts', -1).limit(50).exec(function(err, orders) {
      return res.render("manager/list", {
        orders: orders,
        bill_href: function(p) {
          var _ref;
          if ((_ref = p.state) === 'new' || _ref === 'sent') {
            return config.server.baseurl + "bill/" + p.order_id + "-" + p.srand;
          }
        }
      });
    });
  };

  _x.new_order = function(req, res) {
    return res.render("manager/new_order");
  };

  _x.new_order_post = function(req, res) {
    var amount, b;
    b = req.body;
    amount = parseInt(b.amount);
    if (amount > 0) {
      return mdb.inc_counter("order_id", 1, function(err, seq) {
        var order, order_id;
        order_id = new Date().toFormat("YYMMDD") + lib.left_pad(seq, 6);
        order = new mdb.Orders({
          order_id: order_id,
          srand: lib.random_digits(),
          name: b.name,
          email: b.email,
          descr: b.descr,
          amount: amount
        });
        order.save(function(err) {
          if (err != null) {
            return console.log('save err:', err);
          }
        });
        return res.send({
          redir: config.server.baseurl + "manager/"
        });
      });
    } else {
      return res.send({
        err: 1
      });
    }
  };

  _x.send_link = function(req, res) {
    return res.send({
      ok: 1
    });
  };

}).call(this);
