// Generated by CoffeeScript 1.3.3
(function() {
  var config, crypto, du, left_pad, mdb, util, _x;

  util = require('util');

  du = require('date-utils');

  crypto = require('crypto');

  config = require('config');

  mdb = require('./mdb');

  left_pad = function(s, n, c) {
    if (c == null) {
      c = '0';
    }
    return (new Array(n + 1).join(c) + s).substr(-Math.max(n, s.toString().length));
  };

  _x = exports || this;

  _x.paylist = function(req, res) {
    return mdb.Payments.find({}).sort('ts', -1).exec(function(err, pay_list) {
      return res.render("manager/list", {
        pay_list: pay_list
      });
    });
  };

  _x.newpay = function(req, res) {
    return res.render("manager/newpay");
  };

  _x.newpay_post = function(req, res) {
    var amount, b;
    console.log('newpay_post:', req.body);
    b = req.body;
    amount = parseInt(b.amount);
    if (amount > 0) {
      return mdb.inc_counter("merc_id", 1, function(err, seq) {
        var merc_id, pm;
        merc_id = new Date().toFormat("YYMMDD") + left_pad(seq, 6);
        console.log('merc_id:', merc_id);
        pm = new mdb.Payments({
          merc_id: merc_id,
          arius_id: "",
          srand: ("00000000" + parseInt(crypto.randomBytes(4).toString('hex'), 16)).slice(-8),
          name: b.name,
          email: b.email,
          descr: b.descr,
          amount: amount
        });
        pm.save(function(err) {
          if (err != null) {
            return console.log('save err:', err);
          }
        });
        return res.send({
          ok: 1
        });
      });
    } else {
      return res.send({
        ok: 1
      });
    }
  };

  _x.send_link = function(req, res) {
    return res.send({
      ok: 1
    });
  };

}).call(this);
