// Generated by CoffeeScript 1.3.3
(function() {
  var PaymentSchema, Schema, config, mongoose, oid, _x;

  _x = exports || this;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  oid = Schema.ObjectId;

  config = require('config');

  mongoose.connect(config.datasource.url);

  PaymentSchema = new Schema({
    _id: oid,
    state: {
      type: String,
      "default": 'new',
      "enum": ['new', 'sent', 'paid', 'canc', 'del']
    },
    ts: {
      type: Date,
      "default": new Date
    },
    name: String,
    email: String,
    descr: String,
    amount: Number,
    merc_id: String,
    arius_id: String
  });

  _x.Payment = mongoose.model('payment', PaymentSchema);

}).call(this);
