#
#   ariuspay development configuration
#

datasource:
  url: "mongodb://localhost/ariuspay"

arius:
  api_url:  "https://sandbox.ariuspay.ru/paynet/api/v2/"
  endpoint: "161"
  merc_key: "B9903797-8363-44D4-B7A3-60D7F50CA02B"
# test_card: 4444555566661111 (123)




#.