// Generated by CoffeeScript 1.3.3
(function() {
  var post_json, serialize_form;

  serialize_form = function($form) {
    var f, k, res, _i, _len, _ref;
    res = {};
    _ref = $form.serializeArray();
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      f = _ref[_i];
      k = f['name'];
      if (res[k] != null) {
        if (!res[k].push) {
          res[k] = [res[k]];
        }
        res[k].push(f['value']);
      } else {
        res[k] = f['value'];
      }
    }
    return res;
  };

  post_json = function(url, obj, success, error) {
    if (typeof obj !== "string") {
      obj = (obj != null) && JSON.stringify(obj) || "{}";
    }
    return $.ajax({
      type: 'POST',
      contentType: 'application/json',
      url: url,
      data: obj,
      dataType: 'json',
      success: function(data) {
        return success(data);
      },
      error: function(xhr) {
        if (error) {
          return error(xhr);
        }
      }
    });
  };

  $(function() {
    return $("#frm_newpay").submit(function() {
      console.log(serialize_form($(this)));
      post_json('newpay', serialize_form($(this)), function(data) {
        return console.log('reseived', data);
      }, function(xhr) {
        return console.error('ajax error');
      });
      return false;
    });
  });

  $(function() {
    return $("input[type=text]:first").focus();
  });

}).call(this);
